apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-events

resources:
- namespace.yaml
- github.com/argoproj/argo-events/manifests/base/crds?ref=v1.8.1

helmCharts:
- name: argo-events
  releaseName: argo-events
  namespace: argo-events
  repo: https://argoproj.github.io/argo-helm
  version: 2.4.1
  valuesFile: values.yaml
