apiVersion: v1
kind: Service
metadata:
  name: grafana-extname
  annotations:
    external-dns.alpha.kubernetes.io/hostname: grafana.homelab.danmanners.com
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  type: ExternalName
  externalName: nginx.homelab.danmanners.com
  sessionAffinity: None
