apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

helmCharts:
- name: kube-prometheus-stack
  releaseName: kube-prometheus-stack
  namespace: monitoring
  repo: https://prometheus-community.github.io/helm-charts
  version: "52.1.0"
  valuesFile: values.yaml

resources:
- ns.yaml
- external-dns.yaml

components:
- crds
