kubeProxy:
  enabled: true

kube-state-metrics:
  metricLabelsAllowlist:
  - "persistentvolumeclaims=[*]"
  prometheus:
    monitor:
      enabled: true
      relabelings:
      - action: replace
        regex: (.*)
        replacement: $1
        targetLabel: kubernetes_node
        sourceLabels:
        - __meta_kubernetes_pod_node_name

grafana:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: acme-prod
    hosts:
    - grafana.homelab.danmanners.com
    tls:
    - secretName: grafana-cert
      hosts:
      - grafana.homelab.danmanners.com


kubelet:
  enabled: true
  serviceMonitor:
    metricRelabelings:
    - action: replace
      sourceLabels:
      - node
      targetLabel: instance

nodeExporter:
  serviceMonitor:
    relabelings:
    - action: replace
      regex: (.*)
      replacement: $1
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: kubernetes_node

prometheus:
  prometheusSpec:
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    retention: 10d
    retentionSize: "10GB"
    walCompression: true
    resources:
      requests:
        memory: 400Mi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "ceph-rbd"
          resources:
            requests:
              storage: 30Gi

