apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeclarity
  namespace: argocd
spec:
  destination:
    namespace: kubeclarity
    server: https://kubernetes.default.svc
  project: default
  sources:
  # Git Repo Deployment
  - path: manifests/workloads/kubeclarity
    repoURL: https://github.com/danmanners/homelab-kube-cluster.git
    targetRevision: main
  # Helm Repo Ref
  - repoURL: https://github.com/danmanners/homelab-kube-cluster.git
    targetRevision: main
    ref: values
    # Helm Chart Deployment
  - repoURL: https://openclarity.github.io/kubeclarity
    chart: kubeclarity
    targetRevision: v2.22.0
    helm:
      valueFiles:
      - $values/manifests/workloads/kubeclarity/values.yaml
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
