apiVersion: v1
data:
  password: dUJnenFVMWU3N3dQeEpKc29CZzRoQmpwR09keHMx
  username: cG9zdGdyZXM=
kind: Secret
metadata:
  name: postgres-superuser
  namespace: kubeclarity
type: kubernetes.io/basic-auth
