apiVersion: v1
kind: Service
metadata:
  name: kubeclarity-extname
  annotations:
    external-dns.alpha.kubernetes.io/hostname: kubeclarity.homelab.danmanners.com
    external-dns.alpha.kubernetes.io/ttl: "300"
  labels:
    app.kubernetes.io/name: kubeclarity
spec:
  type: ExternalName
  externalName: nginx.homelab.danmanners.com
  sessionAffinity: None
