apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- ns.yaml
- ../00-secrets
- networking

generators:
- secrets-generator.yaml

helmCharts:
- name: argo-cd
  releaseName: argo-cd
  namespace: argocd
  repo: https://argoproj.github.io/argo-helm
  version: "5.51.2"
  valuesFile: values.yaml
