apiVersion: v1
kind: Secret
metadata:
    name: github-oauth
    namespace: argocd
    labels:
        app.kubernetes.io/part-of: argocd
stringData:
    dex.github.clientID: ENC[AES256_GCM,data:gYL8OwFw0OvJtttSuaV/+c2UksI=,iv:qbRO9f032BLINzyi8jn8sPfGoRRNYJT8yYLlfy3z5UI=,tag:4LKGv2AfMyVMVz6FODKnYw==,type:str]
    dex.github.clientSecret: ENC[AES256_GCM,data:oLxd3LSjgSGXdtv5Uqk6ZAzTDSxRI7Mdvc2aIurgGMSZ/msren0Z0g==,iv:4NEv7+U/nluKVW97tcYBb1rpjiY0UfX7Nuq7aJh+mGY=,tag:lL4/3HzQODAs8V9oMeKNGA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:977656673179:key/7e829b85-6fed-4598-b675-8ebeea105c4c
          created_at: "2023-09-08T15:28:48Z"
          enc: AQICAHi1XYvA3EFEGTwFyd0NLI4cRLiZ3o2bNcK2AmDuVl/CEwHMlyLYf5OZbLstQBWrhXwyAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMdctkQzI0ir4XeHF1AgEQgDvCNC40MFppdiTgKVwJIwGTNFAuijvyqjrYXQim/jYdvFkoG80hUIDYP9LGC5OnEDdZpyXCW4v2NaMM1w==
          aws_profile: default
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-09-08T16:39:02Z"
    mac: ENC[AES256_GCM,data:99S9nePEY9cr4Vrymr25CigHozfmkFeNjFN2XUaEVo6HVKwhCG6YDcRwZ3td6Lk5rEOK+jFTeGHe6+gcoccwZN095FsWtnZSQSl8wnjKOPxuvF4YkhHHh17zePD7NfnSz98snKOrW8oBimN7H0is6FwTvQT48nw0Kj6GQc1apWE=,iv:f1N0OPUn2k2bySVkj1ihRIisevkaiF+aIghyvAO0bow=,tag:LCbMRsGhOGw7IjHf1Y/W8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: argo-workflows-sso
    namespace: argocd
    labels:
        app.kubernetes.io/part-of: argocd
stringData:
    client-id: ENC[AES256_GCM,data:caNlw5w6D+b2mxUX+Hbf7t/n,iv:8andsqoRdijzp7Yio+qjw+Tr5jdG1aoxtgtm6xjyj3k=,tag:MFtTdMiuBlcutYgmSc8+QQ==,type:str]
    client-secret: ENC[AES256_GCM,data:8P5P2+BGCBBHRSxUR6nTQ5Jmwwwop49ySJFNb18=,iv:gy1XVbxq0VsvPVhovqEo1pJ5wsOh3FfuWvaQwEj4Zlo=,tag:qaOa1LhNkvoVQO1WL2YmCw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:977656673179:key/7e829b85-6fed-4598-b675-8ebeea105c4c
          created_at: "2023-09-08T15:28:48Z"
          enc: AQICAHi1XYvA3EFEGTwFyd0NLI4cRLiZ3o2bNcK2AmDuVl/CEwHMlyLYf5OZbLstQBWrhXwyAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMdctkQzI0ir4XeHF1AgEQgDvCNC40MFppdiTgKVwJIwGTNFAuijvyqjrYXQim/jYdvFkoG80hUIDYP9LGC5OnEDdZpyXCW4v2NaMM1w==
          aws_profile: default
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-09-08T16:39:02Z"
    mac: ENC[AES256_GCM,data:99S9nePEY9cr4Vrymr25CigHozfmkFeNjFN2XUaEVo6HVKwhCG6YDcRwZ3td6Lk5rEOK+jFTeGHe6+gcoccwZN095FsWtnZSQSl8wnjKOPxuvF4YkhHHh17zePD7NfnSz98snKOrW8oBimN7H0is6FwTvQT48nw0Kj6GQc1apWE=,iv:f1N0OPUn2k2bySVkj1ihRIisevkaiF+aIghyvAO0bow=,tag:LCbMRsGhOGw7IjHf1Y/W8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
