---
# Pipeline - Build a container and push it up to the defined container registry
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-and-build
  namespace: tekton-pipelines
spec:
  # Paramaters
  params:
    - name: gitUrl
      type: string
      default: https://github.com/excalidraw/excalidraw.git
    - name: gitRevision
      type: string
      default: v0.12.0
    - name: containerRegistry
      type: string
      default: ghcr.io
    - name: manifestName
      type: string
      default: excalidraw
    - name: containerName
      type: string
      default: danmanners/excalidraw

  # Workspaces
  workspaces:
    - name: ws
    - name: dockerfile
    - name: containers

  # Steps
  tasks:
    # Initial Step
    - name: clone
      taskRef:
        kind: Task
        name: git-clone
      params:
        - name: url
          value: $(params.gitUrl)
        - name: revision
          value: $(params.gitRevision)
      workspaces:
        - name: output
          workspace: ws

    # Overwrite the original Dockerfile with the modified version
    - name: copy-file
      taskRef:
        kind: ClusterTask
        name: copy-files
      workspaces:
        - name: source
          workspace: dockerfile
        - name: dest
          workspace: ws
      runAfter:
        - clone
      params:
        - name: source-files
          value: Dockerfile
        - name: dest-files
          value: Dockerfile

    # After creating the manifest, build the container images
    - name: amd64
      taskRef:
        kind: ClusterTask
        name: buildah-build
      workspaces:
        - name: source
          workspace: ws
        - name: containers
          workspace: containers
      runAfter:
        - clone
      params:
        - name: IMAGE
          value: "$(params.containerRegistry)/$(params.containerName):$(params.gitRevision)"
        - name: ARCH
          value: amd64
        - name: BUILD_EXTRA_ARGS
          value: "--no-cache"

    # After creating the manifest, build the container images
    - name: arm64
      taskRef:
        kind: ClusterTask
        name: buildah-build
      workspaces:
        - name: source
          workspace: ws
        - name: containers
          workspace: containers
      runAfter:
        - clone
      params:
        - name: IMAGE
          value: "$(params.containerRegistry)/$(params.containerName):$(params.gitRevision)"
        - name: ARCH
          value: arm64
        - name: BUILD_EXTRA_ARGS
          value: "--no-cache"

    # Push up the container images to the image destination
    - name: push
      taskRef:
        kind: ClusterTask
        name: buildah-push
      workspaces:
        - name: containers
          workspace: containers
      runAfter:
        - amd64
        - arm64
      params:
        - name: IMAGE
          value: "$(params.containerRegistry)/$(params.containerName):$(params.gitRevision)"

---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: excalidraw
  generateName: excalidraw-
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-user
  pipelineRef:
    name: clone-and-build
  taskRunSpecs:
    # Build the amd64 image on dedicated amd64 hardware
    - pipelineTaskName: amd64
      taskPodTemplate:
        hostNetwork: true
        nodeSelector:
          kubernetes.io/arch: amd64
    # Build the arm64 image on dedicated arm64 hardware
    - pipelineTaskName: arm64
      taskPodTemplate:
        hostNetwork: true
        nodeSelector:
          kubernetes.io/arch: arm64
    # Faster Networking on the amd64 nodes
    - pipelineTaskName: push
      taskPodTemplate:
        hostNetwork: true
        nodeSelector:
          kubernetes.io/arch: amd64
  workspaces:
    # ConfigMap
    - name: dockerfile
      configMap:
        name: excalidraw
        items:
          - key: excalidraw.Dockerfile
            path: Dockerfile
    # Disk Volumes
    - name: ws
      volumeClaimTemplate:
        spec:
          storageClassName: ceph-filesystem
          accessModes:
            - ReadWriteMany # access mode may affect how you can use this volume in parallel tasks
          resources:
            requests:
              storage: 1Gi
    - name: containers
      volumeClaimTemplate:
        spec:
          storageClassName: ceph-filesystem
          accessModes:
            - ReadWriteMany # access mode may affect how you can use this volume in parallel tasks
          resources:
            requests:
              storage: 5Gi
