---
# Pipeline - Build a container and push it up to the definied container registry
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-and-build
  namespace: tekton-pipelines
spec:
  # Paramaters
  params:
    - name: gitUrl
      type: string
      default: https://github.com/jacebrowning/memegen.git
    - name: gitRevision
      type: string
      default: main
    - name: containerRegistry
      type: string
      default: ghcr.io
    - name: manifestName
      type: string
      default: memegen
    - name: containerName
      type: string
      default: danmanners/memegen

  # Workspaces
  workspaces:
    - name: ws
    - name: containers

  # Steps
  tasks:
    # Initial Step
    - name: clone
      taskRef:
        kind: Task
        name: git-clone
      params:
        - name: url
          value: $(params.gitUrl)
        - name: revision
          value: $(params.gitRevision)
      workspaces:
        - name: output
          workspace: ws

    # Create the Buildah Manifest
    - name: create-manifest
      taskRef:
        kind: ClusterTask
        name: buildah-create-manifest
      workspaces:
        - name: containers
          workspace: containers
      runAfter:
        - clone
      params:
        - name: MANIFEST
          value: $(params.manifestName)

    # After creating the manifest, build the container images
    - name: amd64
      taskRef:
        kind: ClusterTask
        name: buildah-build
      workspaces:
        - name: source
          workspace: ws
        - name: containers
          workspace: containers
      runAfter:
        - create-manifest
      params:
        - name: MANIFEST
          value: $(params.manifestName)
        - name: IMAGE
          value: "$(params.containerRegistry)/$(params.containerName):$(params.gitRevision)"
        - name: STORAGE_DRIVER
          value: vfs
        - name: ARCH
          value: amd64
        - name: DOCKERFILE
          value: Containerfile

    - name: arm64
      taskRef:
        kind: ClusterTask
        name: buildah-build
      workspaces:
        - name: source
          workspace: ws
        - name: containers
          workspace: containers
      runAfter:
        - create-manifest
      params:
        - name: MANIFEST
          value: $(params.manifestName)
        - name: IMAGE
          value: "$(params.containerRegistry)/$(params.containerName):$(params.gitRevision)"
        - name: STORAGE_DRIVER
          value: vfs
        - name: ARCH
          value: arm64
        - name: DOCKERFILE
          value: Containerfile

    # Push up the container images to the image destination
    - name: push
      taskRef:
        kind: ClusterTask
        name: buildah-push
      workspaces:
        - name: source
          workspace: ws
        - name: containers
          workspace: containers
      runAfter:
        - amd64
        - arm64
      params:
        - name: MANIFEST
          value: $(params.manifestName)
        - name: IMAGE
          value: "$(params.containerRegistry)/$(params.containerName):$(params.gitRevision)"

---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: memegen
  generateName: memegen-
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-user
  pipelineRef:
    name: clone-and-build
  taskRunSpecs:
    # Build the amd64 image on dedicated amd64 hardware
    - pipelineTaskName: amd64
      taskPodTemplate:
        # hostNetwork: true
        nodeSelector:
          kubernetes.io/arch: amd64
    # Build the arm64 image on dedicated arm64 hardware
    - pipelineTaskName: arm64
      taskPodTemplate:
        # hostNetwork: true
        nodeSelector:
          kubernetes.io/arch: arm64
    # Faster Networking on the amd64 nodes
    - pipelineTaskName: push
      taskPodTemplate:
        # hostNetwork: true
        nodeSelector:
          kubernetes.io/arch: amd64
  workspaces:
    # Disk Volumes
    - name: ws
      volumeClaimTemplate:
        spec:
          storageClassName: ceph-filesystem
          accessModes:
            - ReadWriteMany # access mode may affect how you can use this volume in parallel tasks
          resources:
            requests:
              storage: 1Gi
      # persistentVolumeClaim:
      # claimName: tekton-builder-memegen
    - name: containers
      volumeClaimTemplate:
        spec:
          storageClassName: ceph-filesystem
          accessModes:
            - ReadWriteMany # access mode may affect how you can use this volume in parallel tasks
          resources:
            requests:
              storage: 2Gi
