---
# Pipeline - Build a container and push it up to the definied container registry
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-and-build
  namespace: tekton-pipelines
spec:
  # Paramaters
  params:
    - name: gitUrl
      type: string
      default: https://github.com/jacebrowning/memegen.git
    - name: gitRevision
      type: string
      default: main
    - name: containerRegistry
      type: string
      default: ghcr.io
    - name: manifestName
      type: string
      default: memegen
    - name: containerName
      type: string
      default: danmanners/memegen

  # Workspaces
  workspaces:
    - name: ws
    # - name: containers

  # Steps
  tasks:
    # Initial Step
    - name: clone
      taskRef:
        kind: Task
        name: git-clone
      params:
        - name: url
          value: $(params.gitUrl)
        - name: revision
          value: $(params.gitRevision)
      workspaces:
        - name: output
          workspace: ws

    # Run Buildah Official Task
    - name: buildah
      taskRef:
        name: buildah
      runAfter:
        - clone
      params:
        - name: IMAGE
          value: "ghcr.io/danmanners/memegen:$(params.gitRevision)"
        - name: DOCKERFILE
          value: "Containerfile"
        - name: BUILD_EXTRA_ARGS
          value: "--jobs=2 --platform=linux/amd64,linux/arm64"
        - name: PUSH_EXTRA_ARGS
          value: "--all"
      workspaces:
        - name: source
          workspace: ws
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: memegen
  generateName: memegen-
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-user
  pipelineRef:
    name: clone-and-build
  taskRunSpecs:
    # Build the amd64 image on dedicated amd64 hardware
    - pipelineTaskName: buildah
      taskPodTemplate:
        nodeSelector:
          kubernetes.io/arch: amd64
  workspaces:
    # Disk Volumes
    - name: ws
      volumeClaimTemplate:
        spec:
          storageClassName: ceph-filesystem
          accessModes:
            - ReadWriteMany # access mode may affect how you can use this volume in parallel tasks
          resources:
            requests:
              storage: 5Gi
