kubeVersion: 1.28
namespace: kube-system

image:
  registry: docker.io

ingress:
  enabled: false
  ingressClassName: nginx

createController: true
secretName: sealed-secrets-key

metrics:
  serviceMonitor:
    enabled: false
    namespace: monitoring
  dashboards:
    create: false
    namespace: monitoring
