apiVersion: v1
kind: Service
metadata:
  name: excalidraw-extname
  annotations:
    external-dns.alpha.kubernetes.io/hostname: excalidraw.homelab.danmanners.com
    external-dns.alpha.kubernetes.io/ttl: "300"
  labels:
    app.kubernetes.io/name: excalidraw
spec:
  type: ExternalName
  externalName: nginx.homelab.danmanners.com
  sessionAffinity: None
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: excalidraw-cert
  namespace: excalidraw
spec:
  commonName: excalidraw.homelab.danmanners.com
  secretName: excalidraw-cert
  dnsNames:
  - excalidraw.homelab.danmanners.com
  issuerRef:
    name: acme-prod
    kind: ClusterIssuer
