apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: excalidraw

resources:
- namespace.yaml
- ingress.yaml

helmCharts:
- name: app-template
  releaseName: excalidraw
  namespace: excalidraw
  repo: https://bjw-s.github.io/helm-charts
  version: 1.5.1
  valuesFile: values.yaml

images:
- name: excalidraw-image:replaceme
  newName: docker.io/excalidraw/excalidraw
  newTag: latest
