global:
  nameOverride: excalidraw

controller:
  replicas: 2

image:
  repository: excalidraw-image
  tag: replaceme
  pullPolicy: IfNotPresent

nodeSelector:
  kubernetes.io/arch: amd64

service:
  main:
    enabled: true
    type: ClusterIP
    ports:
      http:
        port: 80

ingress:
  main:
    enabled: true
    ingressClassName: nginx
    tls:
    - secretName: excalidraw-cert
      hosts:
      - excalidraw.homelab.danmanners.com
    hosts:
    - host: excalidraw.homelab.danmanners.com
      paths:
      - path: /
        pathType: Prefix
        service:
