apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

helmCharts:
- name: cilium
  releaseName: cilium
  namespace: kube-system
  repo: https://helm.cilium.io/
  version: "1.14.4"
  valuesFile: values.yaml
