---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tekton-pipelines

resources:
  - ingress.yaml
  - secrets

helmCharts:
  - name: oauth2-proxy
    releaseName: tekton-oauth2-proxy
    namespace: tekton-pipelines
    repo: https://oauth2-proxy.github.io/manifests
    version: 6.19.0
    valuesFile: values.yaml
