apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: github-rss

resources:
- namespace.yaml
- controller
- crds
- workers

# generators:
# - generator.yaml

components:
- secrets
