apiVersion: v1
kind: Secret
metadata:
    name: artifactory-creds
stringData:
    bootstrap.creds: ENC[AES256_GCM,data:4YU3pgeIAqZw2cPcMenyCEpKDqe6MfWlDMDSf9LBU2BTL1yvMz/ckgpV/yOdBVk=,iv:HvSivE6oC0l/3qeF0bQDqFuT7wYqeBTani5EGQMK844=,tag:MOLeuVKIRDOrH4Na552Uug==,type:str]
    newKey: ENC[AES256_GCM,data:sB4u4po=,iv:JFWrllTj/1UWEwemDNQmoUDr2SaAjyCRgikFz4Zs6mE=,tag:uU3XyYA0l8xez9slYegn9g==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:977656673179:key/7e829b85-6fed-4598-b675-8ebeea105c4c
          created_at: "2022-08-07T17:58:37Z"
          enc: AQICAHi1XYvA3EFEGTwFyd0NLI4cRLiZ3o2bNcK2AmDuVl/CEwGGIwFLhXxsML9Se+f9sJiMAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMbKSAbRBvapGvOUUHAgEQgDt2+XhRhjtzmaACvZhBbq2C79RTibRwIqRMCvVl23R1ZZtZElAl8QpmkGlvD5pRUW1eTHd1Wi1/A6WLDA==
          aws_profile: default
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-10T14:27:02Z"
    mac: ENC[AES256_GCM,data:G1uSYP6WPHTJraKKksIxMOtS1IBvVf9Hmq4UGj64xUVbq1OBishJhg2ODm4NKx0Z5jm5UWDkeiH55CFdAJAbkngz6OboYa1oB6mIPcqgnZUsJMv5vAY2leX/pDURJIv3rf6V5JqzEGKyAOoWhKiK1SwhVMFLgZjRzZ+E35HNBnQ=,iv:HUPRIJsEcW3bJ8mt1RylqRHlPUf/ob/+Gv1ewV9hx/A=,tag:FjWF+tGrModHJpjI4Jg8DA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
