# runnerdeployment.yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: homelab
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
    spec:
      repository: danmanners/homelab-kube-cluster
