---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dex

helmCharts:
  - name: dex
    releaseName: dex
    namespace: dex
    repo: https://charts.dexidp.io
    version: "0.10.0"
    valuesFile: values.yaml

resources:
  - namespace.yaml
  - ingress.yaml

generators:
  - secrets-generator.yaml
