apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: gitdb-superuser
    namespace: git
stringData:
    username: ENC[AES256_GCM,data:Kprkwb0NqII=,iv:WdxunJ6DChHPtCvHN9jYHkbxLKK1J7GIofRbXuNGIKQ=,tag:oh42apXCUGo7l7DCEd8kUw==,type:str]
    password: ENC[AES256_GCM,data:EmbjV4cBJG1zRklQkiNSs+EgKyby+Kk/AGwz+MGtqg==,iv:tczYLQVGd+sBtgmpeAlXPdnDCiAFMdMS5ifJkoiiQxQ=,tag:Oc2AfsJoKQcadUbhgnz9LA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:977656673179:key/7e829b85-6fed-4598-b675-8ebeea105c4c
          created_at: "2023-09-16T03:07:12Z"
          enc: AQICAHi1XYvA3EFEGTwFyd0NLI4cRLiZ3o2bNcK2AmDuVl/CEwFa+mz8yZWoqLmPzfKyNQIcAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDSdGBT/V9XqvarMbAgEQgDtaHYAQwGWb5zZCdeDjAhRQywNCQlPG/6npSHBm3VO+GAVcM7H53OgBkXvHT1DvekKvLdFTlEzsw28ZvA==
          aws_profile: default
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-09-16T05:30:07Z"
    mac: ENC[AES256_GCM,data:y1HfkqEOKeKC9qhKRWp5VDEW7zB6/QKhZePC7HYlOyYnjPgSn7k+dVayMiVYa70hFholohWC89HSQgz7OF7Qf8cJiUu57iEcnJtvtQqCwTcjMcVgj5jJS9WKi79zrp09tbXAfC27x6Y3PqMOvUG9edENplH9MtFcEo7hTGaDMcs=,iv:VnXV/kI5b0WQCKkMpqly6ryft/pIP3i37ChtDlWyn/g=,tag:wmJu7RucGiynakA/OPX9Vw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
