apiVersion: v1
kind: Service
metadata:
  name: webssh-extname
  annotations:
    external-dns.alpha.kubernetes.io/hostname: webssh.homelab.danmanners.com
    external-dns.alpha.kubernetes.io/ttl: "300"
  labels:
    app.kubernetes.io/name: webssh
spec:
  type: ExternalName
  externalName: nginx.homelab.danmanners.com
  sessionAffinity: None
