apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo
  namespace: argocd
spec:
  destination:
    namespace: kargo
    server: https://kubernetes.default.svc
  project: default
  sources:
  # Git Repo Deployment
  - path: manifests/workloads/kargo
    repoURL: https://github.com/danmanners/homelab-kube-cluster.git
    targetRevision: main
  # Helm Repo Ref
  - repoURL: https://github.com/danmanners/homelab-kube-cluster.git
    targetRevision: main
    ref: values
    # Helm Chart Deployment
  - chart: akuity/kargo-charts/kargo
    repoURL: ghcr.io
    targetRevision: 0.1.1-rc.2
    helm:
      valueFiles:
      - $values/manifests/workloads/kargo/values.yaml
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
