---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-talos-cp02
spec:
  restartPolicy: Never
  nodeName: talos-cp02
  containers:
    - name: disk-wipe
      image: docker.io/library/ubuntu:22.10
      securityContext:
        privileged: true
      command: ["/bin/sh", "-c"]
      env:
        - name: DISK
          value: "/dev/sda"
      args:
        [
          "apt update; apt install fdisk gdisk parted udev -y; sgdisk --zap-all $(DISK); dd if=/dev/zero of=$(DISK) bs=1M count=100 oflag=direct,dsync; wipefs -af $(DISK); blkdiscard $(DISK); partprobe $(DISK)",
        ]
---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-talos-wn01
spec:
  restartPolicy: Never
  nodeName: talos-wn01
  containers:
    - name: disk-wipe
      image: docker.io/library/ubuntu:22.10
      securityContext:
        privileged: true
      command: ["/bin/sh", "-c"]
      env:
        - name: DISK
          value: "/dev/nvme1n1"
      args:
        [
          "apt update; apt install fdisk gdisk parted udev -y; sgdisk --zap-all $(DISK); dd if=/dev/zero of=$(DISK) bs=1M count=100 oflag=direct,dsync; wipefs -af $(DISK); blkdiscard $(DISK); partprobe $(DISK)",
        ]
