apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking

resources:
- deployment.yaml
- rbac-apiserverproxy.yaml
- rbac-operator.yaml
- rbac-proxy.yaml
- secret.yaml

images:
- name: k8s-operator:replaceme
  newName: core.harbor.homelab.danmanners.com/docker.io/tailscale/k8s-operator
  newTag: unstable-v1.53
- name: tailscale:replaceme
  newName: core.harbor.homelab.danmanners.com/docker.io/tailscale/tailscale
  newTag: unstable-v1.53
