# https://github.com/tailscale/tailscale/blob/ed1b935238a7c6cce3aa4865aa13181eb679361a/cmd/k8s-operator/deploy/chart/templates/proxy-rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: proxies
  namespace: networking
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: proxies
  namespace: networking
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: proxies
  namespace: networking
subjects:
- kind: ServiceAccount
  name: proxies
  namespace: networking
roleRef:
  kind: Role
  name: proxies
  apiGroup: rbac.authorization.k8s.io
