---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hdd
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs.csi.k8s.io
parameters:
  server: "10.200.0.3"
  share: "/spinning-bois/talos-kubernetes/"
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
  - nolock
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd
provisioner: nfs.csi.k8s.io
parameters:
  server: "10.200.0.3"
  share: "/faster-bois/talos-kubernetes/"
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
  - nolock
  - hard
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd-nrs
provisioner: nfs.csi.k8s.io
parameters:
  server: "10.200.0.3"
  share: "/faster-bois/no-root-squash/"
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
  - nolock
  - hard
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: harbor
provisioner: nfs.csi.k8s.io
parameters:
  server: "10.200.0.3"
  share: "/faster-bois/harbor/"
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
  - nolock
  - hard
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nvme
provisioner: nfs.csi.k8s.io
parameters:
  server: "10.200.0.3"
  share: "/fastest-bois/talos-kubernetes/"
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
  - nolock
  - hard
