apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/tektoncd/pipeline/releases/download/v0.45.0/release.yaml
# - pipelines
# - resolvers

patches:
- path: feature-flags.yaml
  target:
    name: feature-flags
    namespace: tekton-pipelines
