apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rook-ceph

helmCharts:
# Rook Ceph
- name: rook-ceph
  releaseName: rc
  namespace: rook-ceph
  repo: https://charts.rook.io/release
  version: v1.12.7
  valuesInline:
    rook-ceph-operator-5b6cdbf66-mvs7f: true
- name: rook-ceph-cluster
  releaseName: rcc
  namespace: rook-ceph
  repo: https://charts.rook.io/release
  version: v1.12.7
  valuesFile: rcc-values.yaml
