apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
- networking
- certs

generators:
- ksops-generator.yaml

helmCharts:
- name: harbor
  releaseName: harbor
  namespace: kube-system
  repo: https://helm.goharbor.io
  version: 1.13.1
  valuesFile: values.yaml
