apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitdb
  namespace: git
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  storage:
    size: 40Gi
    storageClass: ceph-rbd
  superuserSecret:
    name: gitdb-superuser
  monitoring:
    enablePodMonitor: true
