apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
namespace: git

resources:
- git-cluster.yaml
- initdb.yaml

generators:
- generator.yaml

images:
- name: postgres-init-db
  newName: core.harbor.homelab.danmanners.com/ghcr.io/onedr0p/postgres-initdb
  newTag: "14.8"
