apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-project
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/danmanners/homelab-kube-cluster.git
    path: manifests/workloads/tekton
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: tekton
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
