apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ns.yaml
- chains/argo-project.yaml
- dashboard/argo-project.yaml
- pipelines/argo-project.yaml
- tasks/argo-project.yaml
- triggers/argo-project.yaml
- event-listener/argo-project.yaml
