---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jfrog

helmCharts:
  - name: artifactory-oss
    releaseName: arti
    namespace: jfrog
    repo: https://charts.jfrog.io
    version: "107.41.12"
    valuesFile: values.yaml

resources:
  - ingress.yaml
  - secrets
