apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wikijs
  namespace: argocd
spec:
  destination:
    namespace: wikijs
    server: https://kubernetes.default.svc
  project: default
  sources:
  # Git Repo Deployment
  - path: manifests/workloads/wikijs
    repoURL: https://github.com/danmanners/homelab-kube-cluster.git
    targetRevision: main
    # Helm Repo Ref
  - repoURL: https://github.com/danmanners/homelab-kube-cluster.git
    targetRevision: main
    ref: values
    # Helm Chart Deployment
  - chart: app-template
    repoURL: https://bjw-s.github.io/helm-charts
    targetRevision: 2.0.3
    helm:
      valueFiles:
      - $values/manifests/workloads/wikijs/values.yaml
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
