apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

resources:
- config.yaml
- external-dns.yaml

helmCharts:
- name: app-template
  releaseName: tabby
  namespace: default
  repo: https://bjw-s.github.io/helm-charts
  version: 2.6.0
  valuesFile: values.yaml

images:
- name: tabby:replaceme
  newName: core.harbor.homelab.danmanners.com/docker.io/tabbyml/tabby
  newTag: 0.5.5
