---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

helmCharts:
  - name: reloader
    releaseName: reloader
    namespace: kube-system
    repo: https://stakater.github.io/stakater-charts
    version: 1.0.52
