---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-danmanners-com
spec:
  commonName: grafana.homelab.danmanners.com
  secretName: grafana-danmanners-com
  dnsNames:
    - grafana.homelab.danmanners.com
    - grafana.i.homelab.danmanners.com
  issuerRef:
    name: acme-prod
    kind: ClusterIssuer
