---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

images:
  - name: uptime-kuma-container-image
    newName: docker.io/louislam/uptime-kuma
    newTag: 1.23.4

helmCharts:
  - name: kah-common-chart
    releaseName: uptime-kuma
    namespace: monitoring
    repo: https://k8s-at-home.com/charts
    version: 1.2.2
    valuesFile: values.yaml

resources:
  - ns.yaml
  - ingress.yaml
  - external-svc.yaml
