apiVersion: v1
kind: Service
metadata:
  name: sonarqube-extname
  annotations:
    external-dns.alpha.kubernetes.io/hostname: sonarqube.homelab.danmanners.com
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  type: ExternalName
  externalName: nginx.homelab.danmanners.com
  sessionAffinity: None
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonarqube-cert
spec:
  commonName: sonarqube.homelab.danmanners.com
  secretName: sonarqube-cert
  dnsNames:
  - sonarqube.homelab.danmanners.com
  issuerRef:
    name: acme-prod
    kind: ClusterIssuer
