apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sonarqube

resources:
- secrets
- ns.yaml
- ingress.yaml

helmCharts:
- name: app-template
  releaseName: sonarqube
  namespace: sonarqube
  repo: https://bjw-s.github.io/helm-charts
  version: 1.5.1
  valuesFile: values.yaml

images:
- name: sonarqube-image:replaceme
  newName: docker.io/library/sonarqube
  # newName: core.harbor.homelab.danmanners.com/docker.io/library/sonarqube
  newTag: 10.3.0-community
- name: postgres-init-db
  newName: ghcr.io/onedr0p/postgres-initdb
  # newName: core.harbor.homelab.danmanners.com/ghcr.io/onedr0p/postgres-initdb
  newTag: "14.8"
- name: busybox-image
  newName: docker.io/library/busybox
  # newName: core.harbor.homelab.danmanners.com/docker.io/library/busybox
  newTag: stable

