apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

helmCharts:
- name: ingress-nginx
  releaseName: ingress-nginx
  namespace: kube-system
  repo: https://kubernetes.github.io/ingress-nginx
  version: "4.8.3"
  valuesFile: values.yaml

patches:
- path: patches/ingress-nginx-controller.yaml
