apiVersion: v1
kind: Secret
metadata:
  name: external-dns
stringData:
  creds: ENC[AES256_GCM,data:ND/g1LCZgngsxaVLTRWKcOM2YWeg5E4lPfS/qxHfn2Pj8VFKZCBcUMLjce3asht2vNvR1qIIvA5vPLBhr3jQrLgZhyFu2F5185R1g0j2fO/D2e43jqEoMSPAbot0hhxfCnwWSC/X26ozMLggeMW04+/0xJs=,iv:rQ6kmUeRWqpJ45kERzm3regc+2EW2iqPEhm7MzpJsXs=,tag:zcnR2GgRSrkw+/EubNaiEA==,type:str]
sops:
  kms:
  - arn: arn:aws:kms:us-east-1:977656673179:key/7e829b85-6fed-4598-b675-8ebeea105c4c
    created_at: "2023-08-02T01:52:26Z"
    enc: AQICAHi1XYvA3EFEGTwFyd0NLI4cRLiZ3o2bNcK2AmDuVl/CEwGRInjZrDKhTHMEe4e9mH5MAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMokmz7KwfW40qShbiAgEQgDvNrrscRZmnjs+cGYakXI5PTH/s/Dag7J+RXjr5q+lSag7hxBtVvJHq/S7ONAYs6NHp3MKfl6UF++rQ4g==
    aws_profile: default
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2023-08-02T01:52:26Z"
  mac: ENC[AES256_GCM,data:QGgHWt86UwSMX+FUVjDKVX2mvE1gVAqb+w+rkeRpiZ7ZnreD1wdGf2L1FHMhEnQnoRrRNHSfpHDCiuc9yIXLYzbI4aP31F69x12v3nnLwmBiUxlENzbnutq5Gr22snzHGNqn0saH/Nv2xqKHne9bj0b9W/y0pXP1RLN3NhuH/Fc=,iv:c02XpkumZDXU4cYAyQtwrfo1aIr1dQzoB4CV0wCa9DE=,tag:azXTHYxnh2M4A7hcVE/3iw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
