apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ns.yaml
- sa.yaml
- rbac.yaml
- networking
# - dexidp

generators:
- secrets-generator.yaml

helmCharts:
- name: argo-workflows
  releaseName: argo-workflows
  namespace: argo-workflows
  repo: https://argoproj.github.io/argo-helm
  version: 0.39.3
  valuesFile: values.yaml
