---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: harbor

helmCharts:
  - releaseName: harbor
    name: harbor
    namespace: harbor
    repo: https://helm.goharbor.io
    version: "1.10.0"
    valuesFile: values.yaml
