apiVersion: v1
kind: Service
metadata:
  name: harbor-extname
  annotations:
    external-dns.alpha.kubernetes.io/hostname: core.harbor.homelab.danmanners.com
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  type: ExternalName
  externalName: nginx.homelab.danmanners.com
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: notary-extname
  annotations:
    external-dns.alpha.kubernetes.io/hostname: notary.harbor.homelab.danmanners.com
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  type: ExternalName
  externalName: nginx.homelab.danmanners.com
  sessionAffinity: None
