---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

helmCharts:
  ## ~9.06TiB Bulk Storage; 7200 RPM HDDs
  - name: nfs-subdir-external-provisioner
    releaseName: hdd
    namespace: kube-system
    repo: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
    version: 4.0.17
    valuesFile: values.yaml
    valuesInline:
      nfs:
        path: "/spinning-bois/talos-kubernetes/"
      storageClass:
        name: hdd
        defaultClass: true
  ## 512GiB SSDs
  - name: nfs-subdir-external-provisioner
    releaseName: ssd
    namespace: kube-system
    repo: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
    version: 4.0.17
    valuesFile: values.yaml
    valuesInline:
      nfs:
        path: "/faster-bois/talos-kubernetes/"
      storageClass:
        name: ssd
  ## 512GiB Intel NVMe Disks
  - name: nfs-subdir-external-provisioner
    releaseName: nvme
    namespace: kube-system
    repo: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
    version: 4.0.17
    valuesFile: values.yaml
    valuesInline:
      nfs:
        path: "/fastest-bois/talos-kubernetes/"
      storageClass:
        name: nvme
