apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: danmanners-dot-com
  namespace: danmanners-dot-com
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: danmanners-dot-com
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      # scale up if usage is above
      # 99% of the requested CPU (10m)
      targetAverageUtilization: 99
