apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jenkins-cert
spec:
  secretName: jenkins-cert
  dnsNames:
  - jenkins.homelab.danmanners.com
  issuerRef:
    name: acme-prod
    kind: ClusterIssuer
