apiVersion: v1
kind: Service
metadata:
  name: jenkins-extname
  annotations:
    external-dns.alpha.kubernetes.io/hostname: jenkins.homelab.danmanners.com
    external-dns.alpha.kubernetes.io/ttl: "300"
  labels:
    app.kubernetes.io/instance: jenkins
spec:
  type: ExternalName
  externalName: nginx.homelab.danmanners.com
  sessionAffinity: None
