apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jenkins

resources:
- ns.yaml
- rbac.yaml
- certs.yaml
- ingress.yaml

helmCharts:
- name: app-template
  releaseName: jenkins
  namespace: jenkins
  repo: https://bjw-s.github.io/helm-charts
  version: 1.5.1
  valuesFile: values.yaml

images:
- name: jenkins-container-image:latest
  newName: core.harbor.homelab.danmanners.com/docker.io/jenkins/jenkins
  newTag: 2.414.3-lts
- name: busybox-image
  newName: core.harbor.homelab.danmanners.com/docker.io/library/busybox
  newTag: stable
