apiVersion: v1
kind: ServiceAccount
# automountServiceAccountToken: true
metadata:
  name: default
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: default.service-account-token
  annotations:
    kubernetes.io/service-account.name: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-user
roleRef:
  name: jenkins
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: default
  kind: ServiceAccount
  namespace: default
