apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: postgres
stringData:
    username: ENC[AES256_GCM,data:uOVnQMG2QfI=,iv:bwQLMOsNQ6seiuPAmYLzvMjmT8YnmcSK5I5c9yditUk=,tag:9W7+vuuROaMe0TMquBvfCA==,type:str]
    password: ENC[AES256_GCM,data:waYS0nH5flKgFXNPFi4Hi9Hqquztz4p+VCS7Cljz,iv:9+7UAhMedcMpjGL6XTeyjg9W1ERWGPGrNRllsePWm9k=,tag:VHzHwCBD1q2we+9Csd9cvQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:977656673179:key/7e829b85-6fed-4598-b675-8ebeea105c4c
          created_at: "2022-08-07T01:14:53Z"
          enc: AQICAHi1XYvA3EFEGTwFyd0NLI4cRLiZ3o2bNcK2AmDuVl/CEwH4oNeq/aD2f4W82X+ng/kjAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM4eSL/ykD8LLM6GwHAgEQgDt4NPADOBTCz/JPKJ6wpgfB2N2X2NglD92M3av8Ckk7p6MXB+GOLX0L0CQhdCTY5ry1BB5ucSmkwA2Evw==
          aws_profile: default
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-07T01:14:53Z"
    mac: ENC[AES256_GCM,data:AzZAo/XRiimOSnbi34BIeULJH5G7VjqhD2mKPrpDNHh2s50qLKDkg0nQ66zuotSP77kgZV3Mz8UT1wv16/c64tczf5WTWCR3aix4+bopHupZg2aQU1P9KPfGiIDzcCvT5DKmHx9gIfWlsRDeuIAZ49E3335OVe9ov2m+KCzUaOM=,iv:CB+ftd7N0HclhfC6t7gWnwJl1a5Jfdq5PEVLq/66Fsk=,tag:V2juLR+Rxvl8qG4I0+eSiw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
