apiVersion: apps/v1
kind: Deployment
metadata:
  name: route53-sync
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: route53-sync
  template:
    metadata:
      labels:
        app: route53-sync
    spec:
      containers:
      - name: route53-sync
        image: ghcr.io/danmanners/r53-updater:latest
        imagePullPolicy: Always
        securityContext:
          runAsUser: 10001
        args:
        - --hosted-zone-id=$(AWS_HOSTED_ZONE_ID)
        - --hostname=$(HOSTNAME)
        - --ttl=300
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
        env:
        - name: AWS_DEFAULT_REGION
          value: us-east-1
        - name: AWS_HOSTED_ZONE_ID
          value: Z081932343XEULDET1H8
        - name: HOSTNAME
          value: nginx.homelab.danmanners.com
        - name: AWS_CONFIG_FILE
          value: /app/.aws/credentials
        volumeMounts:
        - name: aws-credentials
          mountPath: /app/.aws/credentials
          readOnly: true
          subPath: creds
      volumes:
      - name: aws-credentials
        secret:
          secretName: external-dns
