txtOwnerId: onprem-homelab
txtPrefix: txt.
registry: txt
domainFilters:
- homelab.danmanners.com
sources:
- service

policy: upsert-only
interval: 30s

provider: aws
extraArgs:
- --aws-zone-type=public

env:
- name: AWS_DEFAULT_REGION
  value: us-east-1
- name: AWS_SHARED_CREDENTIALS_FILE
  value: /.aws/credentials

extraVolumeMounts:
- name: aws-credentials
  mountPath: /.aws/credentials
  readOnly: true
  subPath: creds

extraVolumes:
- name: aws-credentials
  secret:
    secretName: external-dns

crd:
  create: true
