apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres

helmCharts:
- name: cloudnative-pg
  releaseName: cnp
  namespace: postgres
  repo: https://cloudnative-pg.github.io/charts
  version: 0.19.1
  valuesInline:
    monitoring:
      podMonitorEnabled: true
