---
kind: Kustomization
namespace: kube-system

helmCharts:
  - name: node-feature-discovery
    releaseName: node-feature-discovery
    repo: https://kubernetes-sigs.github.io/node-feature-discovery/charts
    version: "0.11.2"
    valuesInline:
      master:
        affinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: topology.kubernetes.io/zone
                labelSelector:
                  matchExpressions:
                  - key: security
                    operator: In
                    values:
                    - S2
      # worker:
      #   tolerations:
      #     - key: "node-role.kubernetes.io/cloud"
      #       operator: "Equal"
      #       value: ""
      #       effect: "NoSchedule"

resources:
  - nfd-worker-conf-cm.yaml
