apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: github

resources:
- namespace.yaml
- runners/homelab-kube-cluster.yaml

generators:
- generator.yaml

helmCharts:
- name: actions-runner-controller
  releaseName: arc
  namespace: github
  repo: https://actions-runner-controller.github.io/actions-runner-controller
  version: 0.23.5
  valuesFile: values.yaml
