apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: danmanners.homelab-kube-repo
  namespace: github-rss
releaseName: danmanners.homelab-kube-repo
name: gha-runner-scale-set
namespace: github-rss
version: 0.6.0
valuesMerge: merge
valuesInline:
  githubConfigUrl: https://github.com/danmanners/homelab-kube-cluster
  githubConfigSecret: controller-manager
  # githubConfigSecret:
  #   github_app_id: "fake"
  #   github_app_installation_id: "fake"
  #   github_app_private_key: |
  #     fake key here

  controllerServiceAccount:
    name: github-rss-controller
    namespace: github-rsss
