apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

helmCharts:
- name: nvidia-device-plugin
  releaseName: nvidia-device-plugin
  namespace: kube-system
  repo: https://nvidia.github.io/k8s-device-plugin
  version: 0.14.3
  valuesInline:
    runtimeClassName: nvidia
    gfd:
      enabled: true
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            # On discrete-GPU based systems NFD adds the following label where 10de is the NVIDIA PCI vendor ID
            - key: feature.node.kubernetes.io/pci-10de.present
              operator: In
              values:
              - "true"
          - matchExpressions:
            # On some Tegra-based systems NFD detects the CPU vendor ID as NVIDIA
            - key: feature.node.kubernetes.io/cpu-model.vendor_id
              operator: In
              values:
              - "NVIDIA"
          - matchExpressions:
            # We allow a GPU deployment to be forced by setting the following label to "true"
            - key: "nvidia.com/gpu.present"
              operator: In
              values:
              - "true"

