apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: acme-prod
spec:
    acme:
        email: daniel.a.manners@gmail.com
        preferredChain: ""
        privateKeySecretRef:
            name: acme-prod-account-key
        server: https://acme-v02.api.letsencrypt.org/directory
        solvers:
            - dns01:
                route53:
                    accessKeyID: ENC[AES256_GCM,data:JeFF1rvAZKVhnzNmmEDFocVbXrk=,iv:7U3IsLDmY1yBSK5KrE+f/MnIFeup8czeJyGKgn11jPU=,tag:kQIsYD7bO5yzllNcRqukcw==,type:str]
                    region: us-east-1
                    secretAccessKeySecretRef:
                        name: aws-creds
                        key: certmanager
              selector:
                dnsZones:
                    - homelab.danmanners.com
                    - danmanners.io
                    - k3s.danmanners.io
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:977656673179:key/7e829b85-6fed-4598-b675-8ebeea105c4c
          created_at: "2023-02-18T23:58:29Z"
          enc: AQICAHi1XYvA3EFEGTwFyd0NLI4cRLiZ3o2bNcK2AmDuVl/CEwF3c5+MuwdSSKyWSAzJRClOAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM7ALLn6D7p4tk9zOyAgEQgDvBX62gYI2yRFmxX66bRbaQJv8e8rfxyb+xMYlCpsdv+8r8FQcDllSFV5xw29ffNL9vCu5tSDDMThMFzQ==
          aws_profile: default
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-07-24T00:53:39Z"
    mac: ENC[AES256_GCM,data:K8oE4/EyVZDLxZF/MynYlhJHrzzArz83MUqXxlkCwj0SXnkfkGBTEBiPfSUaekJPNQEQAhH7ipi2bMT7eBLhRoa9jv6RDzc+WKqxEAgldNif0O3uvn/jXTN8+n5V4pc2zzPqadAAI4ZVmNf5UcOyGechSU4KRxbK6URtlYAE+Oc=,iv:atYyHau4oAhz9Fx4GnT+hzYhOPkwuLvPbE0JFs/P670=,tag:2Vs1SHgd0sxdXFNDTvhGzw==,type:str]
    pgp: []
    encrypted_regex: ^(accessKeyID)$
    version: 3.7.3
