apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

helmCharts:
- name: cert-manager
  releaseName: cert-manager
  namespace: kube-system
  repo: https://charts.jetstack.io
  version: "v1.13.2"
  valuesInline:
    installCRDs: false
    extraArgs:
    - --dns01-recursive-nameservers=1.1.1.1:53,9.9.9.9:53
    - --dns01-recursive-nameservers-only
    podDnsPolicy: None
    podDnsConfig:
      nameservers:
      - "1.1.1.1"
      - "9.9.9.9"

resources:
- ../00-secrets
- self-signed-cluster-issuer.yaml
- https://github.com/cert-manager/cert-manager/releases/download/v1.12.3/cert-manager.crds.yaml

generators:
- ksops-generator.yaml
