apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pxeboot

resources:
- namespace.yaml
- ingress-basicauth.yaml

helmCharts:
- name: app-template
  releaseName: pxe
  namespace: pxe
  repo: https://bjw-s.github.io/helm-charts
  version: 1.5.1
  valuesFile: values.yaml

images:
- name: pxe:replaceme
  newName: core.harbor.homelab.danmanners.com/ghcr.io/netbootxyz/netbootxyz
  newTag: 0.6.8-nbxyz4

patches:
- patch: |
    apiVersion: v1
    kind: Service
    metadata:
      name: pxe
    spec:
      loadBalancerClass: metallb
