apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: nda
  namespace: nda
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nda
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70
