apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

helmCharts:
- name: coredns
  releaseName: dns
  namespace: kube-system
  repo: https://coredns.github.io/helm
  version: 1.28.1
  valuesFile: values.yaml

