---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kyverno

resources:
  - rbac.yaml

helmCharts:
  - name: kyverno
    releaseName: kyverno
    namespace: kyverno
    repo: https://kyverno.github.io/kyverno
    version: v2.5.3
    valuesFile: values.yaml
