apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-tasks
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/danmanners/homelab-kube-cluster.git"
    path: manifests/workloads/tekton/tasks
    targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: tekton-pipelines
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
