apiVersion: v1
kind: Service
metadata:
  name: spiderfoot-extname
  annotations:
    external-dns.alpha.kubernetes.io/hostname: spiderfoot.homelab.danmanners.com
    external-dns.alpha.kubernetes.io/ttl: "300"
  labels:
    app.kubernetes.io/name: spiderfoot
spec:
  type: ExternalName
  externalName: nginx.homelab.danmanners.com
  sessionAffinity: None
