FROM docker.io/library/alpine:3.17.0

# Args
ARG ARCH
ARG KUBECTL_VERSION
ARG KUSTOMIZE_VERSION
ARG HELM_VERSION
ARG SOPS_VERSION
ARG KSOPS_VERSION
ARG TALOSCTL_VERSION
ARG APP_PATH="/usr/local/bin"
# Envs
ENV ARCH=${ARCH:-amd64}
ENV SOPS_VERSION=${SOPS_VERSION:-v3.7.3}
ENV KSOPS_VERSION=${KSOPS_VERSION:-3.0.2}
ENV KUBECTL_VERSION=${KUBECTL_VERSION:-v1.26.0}
ENV HELM_VERSION=${:-v3.11.0}
ENV KUSTOMIZE_VERSION=${:-v4.5.7}
ENV TALOSCTL_VERSION=${TALOSCTL_VERSION:-v1.2.8}
ENV XDG_CONFIG_HOME=${HOME}/.config/
ENV KSOPS_PLUGIN_PATH="${XDG_CONFIG_HOME}/kustomize/plugin/viaduct.ai/v1/ksops/"

# Install Required Pakckages
RUN apk add --no-cache \
    curl git tar openssh aws-cli

# Install Kubectl
RUN \
    curl -fsSL -o ${APP_PATH}/kubectl "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/${ARCH}/kubectl" && \
    chmod +x ${APP_PATH}/kubectl

# Install Kustomize
RUN curl -sL https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2F${KUSTOMIZE_VERSION}/kustomize_${KUSTOMIZE_VERSION}_linux_${ARCH}.tar.gz | \
    tar -zxvf - && mv kustomize ${APP_PATH}/kustomize && chmod +x ${APP_PATH}/kustomize

# Install SOPS
RUN curl -sLo ${APP_PATH}/sops https://github.com/mozilla/sops/releases/download/${SOPS_VERSION}/sops-${SOPS_VERSION}.linux.${ARCH} && \
    chmod a+x ${APP_PATH}/sops

# Install Helm
RUN curl -sLo- https://get.helm.sh/helm-${HELM_VERSION}}-linux-${ARCH}.tar.gz | \
    tar -zxvf - && mv linux-${ARCH}/helm /usr/local/bin/helm && rm -rf linux-${ARCH}

# Install KSOPS
RUN mkdir -p ${KSOPS_PLUGIN_PATH} && \
    curl -sL https://github.com/viaduct-ai/kustomize-sops/releases/download/v${KSOPS_VERSION}/ksops_${KSOPS_VERSION}_Linux_x86_64.tar.gz | \
    tar -zxvf - -C ${KSOPS_PLUGIN_PATH} && chown -R root:root ${KSOPS_PLUGIN_PATH}

# Install Talosctl
RUN curl -sLo ${APP_PATH}/talosctl https://github.com/siderolabs/talos/releases/download/${TALOSCTL_VERSION}/talosctl-linux-${ARCH} && \
    chmod +x ${APP_PATH}/talosctl

# Compress everything; wildin' over here
RUN apk add --no-cache upx && \
    for item in kustomize kubectl sops talosctl ${KSOPS_PLUGIN_PATH}/ksops; do upx $(which ${item}); done && \
    apk del upx

# Let's make sure nothing crashes here
RUN kubectl version --client && \
    kustomize version && \
    sops --version && \
    talosctl version --client

# Finally, add the script to the root of the container
COPY init.sh /init.sh
