apiVersion: v1
kind: Service
metadata:
  name: gitea-extname
  annotations:
    external-dns.alpha.kubernetes.io/hostname: git.homelab.danmanners.com
    external-dns.alpha.kubernetes.io/ttl: "300"
  labels:
    app.kubernetes.io/name: gitea
spec:
  type: ExternalName
  externalName: nginx.homelab.danmanners.com
  sessionAffinity: None
