replicaCount: 1 # Without a RWX storageclass, we can't run more than one replica. RIParoni-Pepperoni.

global:
  imageRegistry: core.harbor.homelab.danmanners.com/docker.io
  storageClass: ceph-rbd

# image:
#   rootless: false

persistence:
  storageClass: ceph-rbd
  size: 60Gi
  accessModes:
  - ReadWriteOnce

strategy:
  type: Recreate # Cant use RollingUpdate because we only have one replica.
  maxUnavailable: 0 # Can't use 1 because we only have one replica.

gitea:
  admin:
    existingSecret: gitea-creds
  config:
    APP_NAME: "Not Your Mommas's GitHub"
    cron.GIT_GC_REPOS:
      ENABLED: false
  additionalConfigSources:
  - configMap:
      name: gitea-app-ini-plaintext
  additionalConfigFromEnvs:
  - name: GITEA__DATABASE__DB_TYPE
    value: postgres
  - name: GITEA__DATABASE__HOST
    value: gitdb-rw.git.svc.cluster.local:5432
  - name: GITEA__DATABASE__NAME
    value: gitea
  - name: GITEA__DATABASE__USER
    valueFrom:
      secretKeyRef:
        name: gitdb-user-creds
        key: GITEA_DB_USERNAME
  - name: GITEA__DATABASE__PASSWD
    valueFrom:
      secretKeyRef:
        name: gitdb-user-creds
        key: GITEA_DB_PASSWORD

service:
  http:
    type: ClusterIP
    clusterIP: ""
  ssh:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/allow-shared-ip: "globalingress-10.4.240.2"
      metallb.universe.tf/loadBalancerIPs: 10.4.240.2

ingress:
  enabled: true
  apiVersion: networking.k8s.io/v1
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: acme-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 128m
  hosts:
  - host: git.homelab.danmanners.com
    paths:
    - path: /
      pathType: Prefix
  tls:
  - secretName: gitea-cert
    hosts:
    - git.homelab.danmanners.com

postgresql-ha:
  enabled: false

postgresql:
  enabled: false

